osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: osx

cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder

install:
  - yarn install

script:
  - yarn dist:mac

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
