image: Visual Studio 2017

platform:
  - x64

environment:
  GH_TOKEN:
    secure: AP2pY/+hAqiqUYZetf++PQLqyXKq1VjveAxLaB/v2StBbF5w4Og3NLvQiqza+crC

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn install

build_script:
  - yarn run dist:win

test: off

artifacts:
  - path: dist\*
